version: 0.2
phases:
   pre_build:
     commands:
       - echo "Pré build phase - exemplo baixar dependencias, certificados,  etc"
     build:
      commands:
        - echo  "Buildind"
        - mvn clean compile package
     pos_build:
       commands:
       - echo "Pos Building"
       - mv target/*.war ./ROOT.war
   artifacts:
      files:
        - ROOT.war